### ISSUE TITLE
Rendering error with <br> element

### ISSUE THREAD

**Issue by jasongrout** [mathjax/MathJax-src#348] opened 2019-09-17 10:49 UTC
In the demo page at https://www.mathjax.org/#demo, try rendering `$x$<br>$y$`. You'll see `t.splitText is not a function` in the preview box.

As far as I can tell, this happens somewhere around https://github.com/mathjax/MathJax-src/blob/2b74fc118907d61535906a5399996d87660b817c/ts/handlers/html/HTMLMathItem.ts#L83, and the problem seems to be that the start node is the `<br>` node, not a text node.

**Comment by jasongrout** [comment] 2019-09-17 10:53
FYI, this can show up quite often since markdown line breaks are often rendered as `<br>`, so typesetting after rendering to markdown can involve `<br>` elements.

**Comment by dpvc** [comment] 2019-09-17 10:53
This is a duplicate of mathjax/MathJax#2202, which already has a PR to fix it waiting for review.

(BTW, we are trying to use the the mathjax/MathJax issue tracker for all MathJax issues, both v3 and v2.  It seems simplest for people to have only one place for reporting issues, rather than trying to force them to one place for v3 and another for v2.  I need to set up issue templates here and there to help that along.)

**Comment by jasongrout** [comment] 2019-09-17 10:57
Ah, sorry. I saw the note about that being an automatically generated repo, and thought this was the place for issues.

**Comment by dpvc** [comment] 2019-09-17 11:41
No problem.  There is still a lot of administrative details like that to take care of. Sigh!

**Comment by dpvc** [comment] 2019-09-21 12:47
I'm closing this one in favor of the other version.

**Closed by dpvc** 2019-09-21 12:47 UTC
Labels: duplicate
