### ISSUE TITLE
support for \oiint and \oiiint

### ISSUE THREAD

**Issue by Vincent0706** [mathjax/MathJax-src#865] opened 2022-10-27 03:00 UTC
I found mathjax didn't support for `\oiint` and `\oiiint` . These function is supported in katex. If I open some file edited with katex, these function will report error.

**Comment by pkra** [comment] 2022-10-27 06:38
Duplicate of https://github.com/mathjax/MathJax/issues/566 (where feature requests should be filed). But v4 adds the missing glyphs so support is feasible now.

**Closed** 2023-01-21 20:40 UTC
