### ISSUE TITLE
Large parens missing extender on Edge

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax-src#64] opened 2017-11-10 19:57 UTC
Using https://mathjax.github.io/mj3-demos/mj3-tex2html-global.html, with input

`x = -\left( \begin{array}{cc} a & b \\ c & d\\ x-1 & x_2 +x^{3^4} \\ z 4\\ a & b\end{array}  \right)`

the extender is missing in **Edge** (Microsoft Edge 38.14393.0.0; Microsoft EdgeHTML 14.14393). Picture below:

![image](https://user-images.githubusercontent.com/1545836/32676103-368c6826-c60e-11e7-975a-051e82e75fd5.png)

Some other stretchy delims (left { and completely missing right vertical line):
`x = -\left\{ \begin{array}{cc} a & b \\ c & d\\ x-1 & x_2 +x^{3^4} \\ z 4\\ a & b\end{array}  \right|`

![image](https://user-images.githubusercontent.com/1545836/32676193-90fbf52e-c60e-11e7-94c3-5794540f62a1.png)

**Comment by zorkow** [comment] 2017-11-10 20:02
The bug with braces also occurs on Firefox and Chrome. Other extenders are fine, though.

**Comment by pkra** [comment] 2017-11-13 17:51
This reminds me of problems I saw early on so I'm not sure if the build is perhaps out of date. Could you try build a fresh one?

Another random idea would be check if webfonts vs local fonts matter (I remember seeing similar issues in other projects).

FYI Davide has taken a look but can't reproduce.

**Comment by dpvc** [comment] 2017-11-14 11:46
I suspect that the build is not up to date in some way as well.  I will try to make a new one locally myself and see what happens.

As for the fonts, I'm pretty sure local fonts are not used, even if installed, for this version of the CSS.

**Comment by pkra** [comment] 2017-11-14 12:51
@dpvc I'm reasonably sure I merged `stretchy-cells` and `tex_input_typescript` branches. Are those not the latest?

**Comment by zorkow** [comment] 2017-11-14 12:58
We've played with the demo linked from the demo repo.

**Comment by dpvc** [comment] 2017-11-14 13:00
I was wondering if you ran `tsc` after the merge, or after checking out your branch.  I've fallen for that repeatedly myself, and gotten weird results due to partially compiled (or differently compiled) pieces.  There are also some small corrections in some other branches based on Volker's reviews.  And one other branch that is from master to master not in stretchy-cells.

**Comment by pkra** [comment] 2017-11-14 13:41
@dpvc wrote 

> I was wondering if you ran tsc after the merge, or after checking out your branch. 

Could be though I tried to prevent this -- here's the installation script that should be run to update the dists https://github.com/mathjax/mj3-demos/blob/master/install.sh.

I've re-built the TeX-based builds and saw changes (but since they're not in the MML dists I doubt they come from the HTML output).

 I've pushed an update to the mj3-demos repository and still see the issue in Edge.

**Comment by pkra** [comment] 2017-11-16 17:49
This should be fixed now.

**Comment by dpvc** [comment] 2017-11-16 17:56
Did you actually check that it works on Edge?  I need to update my copy before I can do proper testing of the changes.

**Comment by zorkow** [comment] 2017-11-16 21:14
Works for me now. There are a couple of (very) minor alignment issues on Chrome, but looks great in Firefox.

**Comment by pkra** [comment] 2017-11-17 10:00
> Did you actually check that it works on Edge?

Yes, I did.

**Comment by dpvc** [comment] 2017-11-17 11:30
> Yes, I did.

Great!  Thanks.  I was thinking I would still need to look into that, so I'm glad the fixes for other things took care of that as well.

**Comment by NSoiffer** [comment] 2017-11-18 05:30
Thing are much better, but there is still a problem in Edge. Using https://mathjax.github.io/mj3-demos/mj3-tex2html-global.html (which I think must have been rebuilt given that it is so much better). Using 
`x = -\left( \begin{array}{cc} a & b \\ c & d\\ x-1 & x_2 +x^{3^4} \\ z 4\\ a & b\end{array} \right) + x = -\left\{ \begin{array}{cc} a & b \\ c & d\\ x-1 & x_2 +x^{3^4} \\ z 4\\ a & b\end{array} \right|`
as input...

Edge (missing part of `{`):
![image](https://user-images.githubusercontent.com/1545836/32977235-1e8e595c-cbde-11e7-8c24-47a190b835d1.png)

Chrome (extenders in `{` are off by one):
![image](https://user-images.githubusercontent.com/1545836/32977242-426e5f16-cbde-11e7-96aa-8407ddbd4e39.png)

Firefox/quantum (parens are off by one):
![image](https://user-images.githubusercontent.com/1545836/32977246-5fb5e2b0-cbde-11e7-99c4-354830b41e96.png)

**Comment by pkra** [comment] 2017-12-08 08:40
More improvements are in the latest alpha.

**Comment by dpvc** [comment] 2021-04-14 14:01
I believe this is now resolved (as of #675).

**Closed by dpvc** 2021-04-14 14:01 UTC
