### ISSUE TITLE
The rendering results of `\sin x^2` and `\sin {x}^{2}` should be the same, but not

### ISSUE THREAD

**Issue by YiNiCoo** [mathjax/MathJax-src#382] opened 2019-11-06 11:23 UTC
The rendering results of `\sin x^2` and `\sin {x}^{2}` should be the same, but not. One space is missing.

**Comment by dpvc** [comment] 2019-11-06 11:28
This is a duplicate of mathjax/MathJax#2187, and is fixed in PR #344 

On a side note, please report bugs in the mathjax/MathJax issue tracker (so all the bugs ore in one place) rather than on the MathJax-src issue tracker.  Thanks!

**Comment by YiNiCoo** [comment] 2019-11-06 11:37
OK

**Closed** 2019-11-18 03:30 UTC
Labels: duplicate
